Remove PCAP calls
Fix compiler error:
dyplocontext.cpp:12:21: error: 'class dyplo::HardwareContext' has no member named 'setProgramMode'

Even on the Zynq we no longer use the PCAP.